server:
  port: 8081
spring:
  application:
    name: "Solicitudes"
  devtools:
    add-properties: false
  webflux:
    base-path: "/api"
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapters:
  r2dbc:
    host: "${R2DBC_HOST_REQ:localhost}"
    port: "${R2DBC_PORT_REQ:5432}"
    database: "${R2DBC_DATABASE_REQ:pragma}"
    schema: "${R2DBC_SCHEMA_REQ:solicitudes}"
    username: "${R2DBC_USERNAME_REQ:postgres}"
    password: "${R2DBC_PASSWORD_REQ:1234}"
security:
  jwt:
    secretkey: "${JWT_SECRET_KEY:Bardelhaus1234567890Bardelhaus1234567890$}"
  user:
    admin: "${USER_ADMIN:jandreaj100@gmail.com}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapter:
  restconsumer:
    timeout: 5000
    url: "${REST_URL:http://localhost:8080/api}"
    path: "${REST_PATH:v1/usuarios/por-correos}"
  sqs:
    validacion:
      region: "${SQS_REGION:us-east-2}"
      queueUrl: "${SQS_SEND_VALIDACION_QUEUE:https://sqs.us-east-2.amazonaws.com/096212910572/Solicitudes.fifo}"
      endpoint: "${SQS_ENDPOINT:https://sqs.us-east-2.amazonaws.com}"
    respuesta:
      region: "${SQS_REGION:us-east-2}"
      queueUrl: "${SQS_SEND_RESPUESTA_QUEUE:https://sqs.us-east-2.amazonaws.com/096212910572/Respuesta.fifo}"
      endpoint: "${SQS_ENDPOINT:https://sqs.us-east-2.amazonaws.com}"
  sns:
    region: "${SNS_REGION:us-east-2}"
    topicArn: "${SNS_TOPIC_ARN:arn:aws:sns:us-east-2:096212910572:notificarEstadoFinal}"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
entrypoint:
  sqs:
    region: "${SQS_REGION:us-east-2}"
    endpoint: "${SQS_LISTENER_QUEUE:https://sqs.us-east-2.amazonaws.com}"
    queueUrl: "${SQS_LISTENER_ENDPOINT:https://sqs.us-east-2.amazonaws.com/096212910572/RespuestaEstado.fifo}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
