CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA solicitudes AUTHORIZATION postgres;

CREATE TABLE solicitudes.estado (
	id_estado int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombre varchar(255) NOT NULL,
	descripcion varchar(255) NOT NULL,
	constraint estado_pk primary key (id_estado)
);

CREATE TABLE solicitudes.tipo_prestamo (
	id_tipo_prestamo int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombre varchar(255) NOT NULL,
	monto_minimo numeric(15,2) not null,
	monto_maximo numeric(15,2) not null,
	tasa_interes numeric(10,2) not null,
	validacion_automatica bool not null,
	constraint tipo_prestamo_pk primary key (id_tipo_prestamo)
);

CREATE TABLE solicitudes.solicitud (
	id_solicitud int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	monto numeric(10,2) not null,
	plazo int not null,
	email varchar(255) NOT NULL,
	id_estado int8 not null,
	id_tipo_prestamo int8 not null,
	constraint solicitud_pk primary key (id_solicitud),
	CONSTRAINT solicitud_estado_fk FOREIGN KEY (id_estado) REFERENCES solicitudes.estado(id_estado),
    CONSTRAINT solicitud_tipo_prestamo_fk FOREIGN KEY (id_tipo_prestamo) REFERENCES solicitudes.tipo_prestamo(id_tipo_prestamo)
);

INSERT INTO solicitudes.estado (nombre, descripcion) VALUES('PENDIENTE REVISION', 'Pendiente de revision');
INSERT INTO solicitudes.estado (nombre, descripcion) VALUES('RECHAZADA', 'Rechazada');
INSERT INTO solicitudes.estado (nombre, descripcion) VALUES('REVISION MANUAL', 'Revisión manual');
INSERT INTO solicitudes.estado (nombre, descripcion) VALUES('APROBADO', 'Aprobado');


INSERT INTO solicitudes.tipo_prestamo (nombre, monto_minimo, monto_maximo, tasa_interes, validacion_automatica)
VALUES
-- Préstamo de libre inversión
('Libre Inversión', 1000000.00, 50000000.00, 18.50, true),
-- Préstamo de vivienda
('Vivienda', 20000000.00, 500000000.00, 12.00, false),
-- Préstamo de vehículo
('Vehículo', 5000000.00, 150000000.00, 14.75, true),
-- Préstamo estudiantil
('Educación', 500000.00, 50000000.00, 10.50, false),
-- Microcrédito
('Microcrédito', 100000.00, 10000000.00, 22.00, true);
